services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

  node-api:
    build: .
    container_name: node-api-container
    restart: unless-stopped
    mem_limit: 100m
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://mongodb:27017
      DB_NAME: practice
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  mongo-data: